### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Chuckaluphagus** [lionaneesh/RasPod#3]
I'm trying to run RasPod on my Raspberry Pi and it's failing with this output:

pi@raspberrypi ~/Programs/RasPod $ python server.py 
[0x8355c8] inhibit interface error: Failed to connect to the D-Bus session daemon: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
[0x8355c8] main interface error: no suitable interface module
Traceback (most recent call last):
    File "server.py", line 393, in <module>
        rasPod = RasPod('all')
    File "server.py", line 71, in **init**
        self._build_up_playlist()
    File "server.py", line 122, in _build_up_playlist
        filename = unicode(settings.MEDIA_FOLDER) + self.media_files[i]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 88: ordinal not in range(128)

I don't have any knowledge of python, or programming much at all, but it looks to me as if it's failing on a file name with characters it's not expecting.  Is there any way to patch this, or could I at least find out what file name(s) it's failing on?

Thank you for your work on this, it looks useful.

**Comment by pappasadrian** [comment]
I've faced the same problem with a song containing the character é in its name. 

I don't really know python either, wish I could help more.

**Comment by lionaneesh** [comment]
Thanks for reporting. The bug is fixed for me. Feel free to comment, if you are still facing problems.
